<a href="https://colab.research.google.com/github/Tr4velnman/Going-back-to-Zamunda/blob/main/Python_Data_Analysis_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Python list
my_list = [1,2,3,4,5, "Justin", True]
my_list2 = [6,7,8, my_list]

In [18]:
#Import Numpy
import numpy as np

In [22]:
#Create numpy array
np1 = np.array([0,1,"bob",3,4,5,6,7,8,9])
print(np1)
print(np1[2])

['0' '1' 'bob' '3' '4' '5' '6' '7' '8' '9']
bob


In [23]:
# Shape - shows the number of elements in the array like the python len function
print(np1.shape)


(10,)


In [24]:
# Arange
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [29]:
# Step
np3 = np.arange(0, 100, 2)
print(np3)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [30]:
# Zeros
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [32]:
# Multi-Dimensional Arrays with Zeros
np5 = np.zeros((5, 10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [38]:
# Full
np6 = np.full((10), "Bob")
print(np6)

['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']


In [40]:
# Multi-Dimensional Arrays with Full
np7 = np.full((2, 10), "Bob")
print(np7)

[['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']
 ['Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob' 'Bob']]


In [43]:
# Convert Python List to Numpy Array
# my_list
my_list = ["Bob", "Justin"]
np8 = np.array(my_list)
print(np8)
print(my_list)

['Bob' 'Justin']
['Bob', 'Justin']
